//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>

namespace MyTestApp.Pages.Protected.Borrow
{

    public partial class Borrow
    {

        protected global::System.Web.UI.WebControls.Label lblMsg;

        protected global::System.Web.UI.WebControls.DropDownList ddlBooks;

        protected global::System.Web.UI.WebControls.Button btnBorrow;
    }
}
