//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTestApp.Pages.Protected.Book
{

    public partial class Books
    {

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.Button btnCreate;

        protected global::System.Web.UI.WebControls.GridView gvBooks;
    }
}
