//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTestApp.Pages.Protected.Book
{

    public partial class Details
    {

        protected global::System.Web.UI.WebControls.Label lblTitle;

        protected global::System.Web.UI.WebControls.Label lblAuthor;

        protected global::System.Web.UI.WebControls.Label lblCategory;

        protected global::System.Web.UI.WebControls.Label lblISBN;

        protected global::System.Web.UI.WebControls.Label lblAdded;
    }
}
