//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTestApp.Pages.Protected.Book
{

    public partial class Edit
    {

        protected global::System.Web.UI.WebControls.Label lblMsg;

        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        protected global::System.Web.UI.WebControls.DropDownList ddlAuthor;

        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        protected global::System.Web.UI.WebControls.TextBox txtISBN;

        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
