//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>

namespace MyTestApp.Pages.Protected.MyBooks
{

    public partial class MyBooks
    {

        protected global::System.Web.UI.WebControls.GridView gvMyBooks;
    }
}
