//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>

namespace MyTestApp.Pages.Protected.Admin
{

    public partial class Register
    {

        protected global::System.Web.UI.WebControls.Label lblMsg;

        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        protected global::System.Web.UI.WebControls.DropDownList ddlRole;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.TextBox txtConfirm;

        protected global::System.Web.UI.WebControls.Button btnRegister;
    }
}
