//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>

namespace MyTestApp.Pages.Protected.Admin
{

    public partial class Users
    {

        protected global::System.Web.UI.WebControls.GridView gvUsers;
    }
}
